# Generated by Django 5.0.6 on 2024-07-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profile_page',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='author',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.person'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.lecturer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='degree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.person'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.author'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='courses',
            field=models.ManyToManyField(blank=True, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='header',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='slide',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.presentation'),
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.presentation')),
            ],
        ),
    ]
